name: CICD

on: 
# add the manual keyword for delivery
  workflow_dispatch:
   inputs:
    enviroment:
      description: this is  the enviroment where the workflow run
      default: 'dev'
      required: true
      type: choice
      options:
        - dev
        - prod
        - staging
      
      
jobs:
#every jobs need seprate runner
#its called as parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: code clone
        run: echo "code clone from git-hub"

  build:
    runs-on: ubuntu-latest
    needs: [code]
    steps:
      - name: build in docker
        run: echo "code container build"


  test:
    runs-on: ubuntu-latest
    needs: [code,build]
    steps:
      - name: testing the container
        run: echo "test the container sucessfully"

  deploy: 
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy in instance
        run: echo "deployed in instance"
  
