# deploy to server using ssh 
#deploying to a server safe/ secure and tested application (help of DevSecOps principles) 
name: deploy to server
on:
    workflow_call:
        secrets:
           EC2_SSH_HOST:
            required: true
           EC2_SSH_PRIVATE_KEY:
            required: true
           EC2_SSH_USERNAME:
            required: true
jobs:
    deploy:
        runs-on: ubuntu-latest       # why we need this  -> for ssh to server side
        steps:
            - name: ssh to production server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                  echo "start deploying"
                  mkdir -p devops


