name: end to end pipline getways        #all devsecops pipline called here
on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
    dependency_scan:
        uses: ./.github/workflows/dependency-scan.yml
    docker_scan:
        uses: ./.github/workflows/docker-lint.yml
    build:
        needs: [code-quality,secrets-scan,dependency_scan,docker_scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
    tiivy_scan:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets:
            inherit


    
